### ISSUE TITLE
Wayland support ?

### ISSUE THREAD

**Issue by AkechiShiro** [winapps-org/WinApps-Launcher#12]
I'm not sure if it possible to port this to Wayland or use xwayland instead of not running at all on Wayland environment (Plasma 6 KDE or GNOME Wayland)

**Comment by KernelGhost** [comment]
@AkechiShiro As far as I know, `yad` doesn't support Wayland natively yet, but it runs well under XWayland. [This comment](https://github.com/v1cont/yad/issues/216#issuecomment-1434702107) suggests a workaround for enabling `yad` notifications on Wayland DEs. Could you confirm if this solution works on your system? I'm currently using XFCE, which doesn't support Wayland yet.

**Comment by redelacruz** [comment]
> @AkechiShiro As far as I know, `yad` doesn't support Wayland natively yet, but it runs well under XWayland. [This comment](https://github.com/v1cont/yad/issues/216#issuecomment-1434702107) suggests a workaround for enabling `yad` notifications on Wayland DEs. Could you confirm if this solution works on your system? I'm currently using XFCE, which doesn't support Wayland yet.

That solution works. Launched using `GDK_BACKEND=x11 ./WinAppsLauncher.sh`. Make sure you don't use `env GDK_BACKEND=x11 ...` This is on Wayland on Pop OS 22.04.

**Comment by AkechiShiro** [comment]
I believe for the rewrite we should use https://alyssa.is/using-virtio-wl/ @LDprg @oskardotglobal @KernelGhost

**Comment by LDprg** [comment]
@AkechiShiro Seems like a great option, however. I am not sure if this is compatible with docker.

**Comment by AkechiShiro** [comment]
My only issue is that Windows might need specific drivers that are not yet written, this is the only pain point I think, I'm not sure if Google has any driver in house that they use, I'd need to contact them

**Comment by AkechiShiro** [comment]
Actually @LDprg I've discussed a bit with someone more familiar with virtio_wl and it is deprecated, we'll need to look for something else. And it definitely wouldn't be usable on Windows at all.

**Comment by AkechiShiro** [comment]
Maybe we should try to see if this could be usable : https://github.com/unified-hmi/remote-virtio-gpu

**Comment by LDprg** [comment]
@AkechiShiro Seems like a great option, however. I am not sure if this is compatible with docker.

**Comment by freechelmi** [comment]
Fixed with #13
